Add --with-qmake6 configure flag when qt5+qt6 are available

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #!/bin/sh
-# This script was automatically generated by ACR v2.1.1
+# This script was automatically generated by ACR v2.1.2
 # @author: pancake <nopcode.org>
 # @url:    http://www.nopcode.org
 # @repo:   git clone https://github.com/radare/acr
@@ -18,6 +18,7 @@ control_c() {
   exit 1
 }
 trap control_c 2
+WANT_QMAKE6=0
 split_host() {
 S="$"
 while : ; do
@@ -92,8 +93,8 @@ create_environ() {
 : ${SBINDIR:="${PREFIX}/sbin"}
 : ${ETCDIR:="${SPREFIX}/etc"}
 : ${LIBDIR:="${SPREFIX}/lib"}
-: ${PKGCFG_LIBDIR:="\${exec_prefix}/lib"}
-: ${PKGCFG_INCDIR:="\${prefix}/include"}
+: ${PKGCFG_LIBDIR:='${exec_prefix}/lib'}
+: ${PKGCFG_INCDIR:='${prefix}/include'}
 : ${LIBEXECDIR:="${SPREFIX}/libexec"}
 : ${INCLUDEDIR:="${SPREFIX}/include"}
 : ${DATADIR:="${SPREFIX}/share"}
@@ -160,6 +161,10 @@ System types:
 EOF2
 
 printf "
+Optional Features:
+  --with-qmake6          ignore qmake in path when qmake6 is found
+"
+printf "
 Some influential environment variables:
   CXX         C++ compiler command
   CXXFLAGS    C++ compiler flags
@@ -192,7 +197,7 @@ if [ "$QUIET" = 1 ]; then
 	echo "5.8.6"
 	exit 0
 fi
-echo "iaito-5.8.6 configuration script done with acr v2.1.1.
+echo "iaito-5.8.6 configuration script done with acr v2.1.2.
 The 'Free Software Foundation' message is only for autodetection.
 Originally written by pancake <nopcode.org>."
 exit 0
@@ -226,6 +231,7 @@ echo "AUTHOR:      pancake"
 echo "EMAIL:       pancake@nopcode.org"
 echo "LANGS:       c++"
 echo "PKGCONFIG:   r_core"
+echo "FLAGS:       --with-qmake6"
 	exit 0
 	;;
 --cache-file)
@@ -277,6 +283,7 @@ echo "PKGCONFIG:   r_core"
 --mandir)
 	MANDIR="$value"; ;;
 
+"--with-qmake6") WANT_QMAKE6="1"; ;;
 *) if [ "$value" ]; then eval "`echo $flag2=$value`" ;
 else echo ; echo "WARNING: Unknown flag '$flag'." >&2 ; echo ; fi ;;
 esac
@@ -294,7 +301,7 @@ parse_options "$1"
 shift
 done
 
-ENVWORDS="MANDIR DESCRIPTION INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR ETCDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGCFG_LIBDIR PKGCFG_INCDIR PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CXX CXXFLAGS LDFLAGS HAVE_LANG_CXX CPP PKGCONFIG HAVE_R2 R2 R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE HAVE_QMAKE QMAKE HAVE_LRELEASE LRELEASE WANT_PYTHON WANT_PYTHON_BINDINGS WANT_CRASH_REPORTS"
+ENVWORDS="MANDIR DESCRIPTION INFODIR LIBDIR INCLUDEDIR LOCALSTATEDIR ETCDIR SYSCONFDIR DATADIR DOCDIR LIBEXECDIR SBINDIR BINDIR EPREFIX PREFIX SPREFIX TARGET HOST BUILD INSTALL INSTALL_LIB INSTALL_MAN INSTALL_PROGRAM INSTALL_PROGRAM_STRIP INSTALL_DIR INSTALL_SCRIPT INSTALL_DATA HOST_OS HOST_CPU BUILD_OS BUILD_CPU TARGET_OS TARGET_CPU VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NUMBER PKGCFG_LIBDIR PKGCFG_INCDIR PKGNAME VPATH CONTACT CONTACT_NAME CONTACT_MAIL CXX CXXFLAGS LDFLAGS HAVE_LANG_CXX CPP PKGCONFIG HAVE_R2 R2 R2_CFLAGS R2_LDFLAGS HAVE_PKGCFG_R_CORE HAVE_QMAKE QMAKE HAVE_QMAKE6 QMAKE6 HAVE_LRELEASE LRELEASE WANT_QMAKE6 QMAKE_BIN WANT_PYTHON WANT_PYTHON_BINDINGS WANT_CRASH_REPORTS"
 
 create_environ
 
@@ -431,9 +438,33 @@ if [ "" = 1 ]; then
 echo "Cannot find qmake" >&2
 else
 echo no
+fi ; fi
+ochof "checking for qmake6... "
+if [ -x "${QMAKE6}" ]; then
+	FIND=${QMAKE6}
+else
+	FIND=""
+	IFS=:
+	for A in ${PATH} ; do
+		if [ -x "${A}/qmake6" ]; then
+			FIND="${A}/qmake6"
+			break;
+		fi
+	done
+	unset IFS
 fi
-	echo "error: This program is required." >&2
-	exit 1 ; fi
+if [ -n "${FIND}" ]; then
+	ocho ${FIND};
+HAVE_QMAKE6=1
+	QMAKE6=${FIND}
+else
+	HAVE_QMAKE6=0
+	QMAKE6=qmake6
+if [ "" = 1 ]; then
+echo "Cannot find qmake6" >&2
+else
+echo no
+fi ; fi
 ochof "checking for lrelease... "
 if [ -x "${LRELEASE}" ]; then
 	FIND=${LRELEASE}
@@ -462,6 +493,17 @@ echo no
 fi
 	echo "error: This program is required." >&2
 	exit 1 ; fi
+if [ "$WANT_QMAKE6" = "1" ]; then
+QMAKE=""; fi
+if [ "$HAVE_QMAKE" = "1" ]; then
+QMAKE_BIN="${QMAKE}"
+else
+if [ "$HAVE_QMAKE6" = "1" ]; then
+QMAKE_BIN="${QMAKE6}"
+else
+case "$undefined_variable" in 0|"") echo ; echo "ERROR: Missing qmake" >&2 ; echo ; exit 1 ;; esac; fi; fi
+if [ "$QMAKE_BIN" = """" ]; then
+case "$undefined_variable" in 0|"") echo ; echo "ERROR: Missing qmake" >&2 ; echo ; exit 1 ;; esac; fi
 WANT_PYTHON="0"
 WANT_PYTHON_BINDINGS="0"
 WANT_CRASH_REPORTS="0"
@@ -509,3 +551,12 @@ done
 done
 
 do_remove
+if [ "$QUIET" = 0 ]; then
+echo
+echo "Final report:"
+for A in  R2 QMAKE_BIN ; do
+eval VAL="\$${A}"
+[ -z "${VAL}" ] && VAL="\"\""
+echo " - ${A} = ${VAL}"
+done
+fi
